
set(NSURFACE_VERSION_MAJOR 0)
set(NSURFACE_VERSION_MINOR 0)
set(NSURFACE_VERSION_PATCH 1)

set(NSURFACE_MAX_VERSION_COMPONENT_VALUE 99)
math(EXPR NSURFACE_VERSION_NUMBER "${NSURFACE_VERSION_MAJOR} * (${NSURFACE_MAX_VERSION_COMPONENT_VALUE} + 1)^2 + ${NSURFACE_VERSION_MINOR} * (${NSURFACE_MAX_VERSION_COMPONENT_VALUE} + 1) + ${NSURFACE_VERSION_PATCH}")

set(NSURFACE_VERSION ${NSURFACE_VERSION_MAJOR}.${NSURFACE_VERSION_MINOR}.${NSURFACE_VERSION_PATCH})
set(ncpp_VERSION ${NSURFACE_VERSION})

set(NSURFACE_VERSION_WITH_UNDERSCORE ${NSURFACE_VERSION_MAJOR}_${NSURFACE_VERSION_MINOR}_${NSURFACE_VERSION_PATCH})

set(NSURFACE_VERSION_${NSURFACE_VERSION_WITH_UNDERSCORE})