
include(NCPP/SetGlobal)
include(NCPP/ApplyGlobal)

NCPP_SetGlobal(NSURFACE_VERSION_MAJOR 0)
NCPP_SetGlobal(NSURFACE_VERSION_MINOR 0)
NCPP_SetGlobal(NSURFACE_VERSION_PATCH 1)

NCPP_SetGlobal(NSURFACE_MAX_VERSION_COMPONENT_VALUE 99)
math(EXPR NSURFACE_VERSION_NUMBER "${NSURFACE_VERSION_MAJOR} * (${NSURFACE_MAX_VERSION_COMPONENT_VALUE} + 1)^2 + ${NSURFACE_VERSION_MINOR} * (${NSURFACE_MAX_VERSION_COMPONENT_VALUE} + 1) + ${NSURFACE_VERSION_PATCH}")
NCPP_ApplyGlobal(NSURFACE_VERSION_NUMBER)

NCPP_SetGlobal(NSURFACE_VERSION ${NSURFACE_VERSION_MAJOR}.${NSURFACE_VERSION_MINOR}.${NSURFACE_VERSION_PATCH})
NCPP_SetGlobal(ncpp_VERSION ${NSURFACE_VERSION})

NCPP_SetGlobal(NSURFACE_VERSION_WITH_UNDERSCORE ${NSURFACE_VERSION_MAJOR}_${NSURFACE_VERSION_MINOR}_${NSURFACE_VERSION_PATCH})

NCPP_SetGlobal(NSURFACE_VERSION_${NSURFACE_VERSION_WITH_UNDERSCORE} "")